### ISSUE TITLE
부장 연락처에 빈 값이 들어 가져요

### ISSUE THREAD

**Issue by chanwoo00106** [GSM-MSG/MSG-BackEnd-V2#141]
# 문제
![image](https://user-images.githubusercontent.com/57276315/172416917-b1e9a8ee-3894-48e6-ba28-dd830634e845.png)

# 해결 방안

> `NotEmpty` 처리를 해줘야 할 것 같아요

**Comment by yoonjibin** [comment]
IsNotEmpty추가했습니다
