### ISSUE TITLE
부장이 자기 자신을 위임하면 동아리에서 부장이 사라져요

### ISSUE THREAD

**Issue by baekteun** [GSM-MSG/MSG-BackEnd-V2#179]
https://github.com/GSM-MSG/MSG-BackEnd-V2/blob/51e5d1be72e9264c775dfdaaafe450557f496f6b/src/Club/club.service.ts#L629-L665

로직이 부장 위임 -> 현 부장을 부장자리에서 강등.
인데 부장이 자기자신을 위임하면 동아리에서 부장이 없어짐

**Comment by Huuuunee** [comment]
근데 생각해보면 headMember는 이메일로 찾는거잖음
