### ISSUE TITLE
네이버 메일 구글 스팸함으로 가는 오류

### ISSUE THREAD

**Issue by chanwoo00106** [GSM-MSG/MSG-BackEnd-V2#52]
# 네이버 메일 구글 스팸함으로 가는 오류

> Gmail은 도메인이 gmail이 아니면 전부 스팸함으로 보낸다고 합니다.
> 그런다고 구글 계정으로 gmail을 보내려고 하니 5월 30일에 `보안 수준이 낮은 앱의 액세스` 기능이 막힌다고 합니다.

[관련 자료](https://support.google.com/accounts/answer/6010255?p=less-secure-apps&hl=ko&visit_id=637864444222738880-224354833&rd=1)

# Solution

> OAuth2를 사용해서 구글에 accessToken과 refreshToken을 발급 받아서 사용하면 `보안 수준이 낮은 앱의 액세스` 기능을 끄고도 Nodemailer로 gmail을 보낼 수 있다고 합니다.

[한글 자료](https://velog.io/@13circle/Nodemailer-X-Gmail-OAuth-2.0)
[영문 자료1](https://www.woolha.com/tutorials/node-js-send-email-using-gmail-with-nodemailer-oauth-2)
[영문자료2](https://dev.to/chandrapantachhetri/sending-emails-securely-using-node-js-nodemailer-smtp-gmail-and-oauth2-g3a)

**Comment by baekteun** [comment]
ㄴㅇㅅ

**Comment by chanwoo00106** [comment]
하지만 내가 안 할 거야
구이찬

**Comment by yoonjibin** [comment]
ㄴㅇㅅ

**Comment by Huuuunee** [comment]
ㄴㅇㅅ
